### ISSUE TITLE
Play next video without delay or black screen

### ISSUE THREAD

**Issue by tino-junge** [tino-junge/cinema-app#12]
Check if loading of next video file could be done faster, e.g. preloaded or appended on current video stream
- A) use an image of first scene of next video 
- B) preload next video in second video div and switch div if first video ends (dirty?)
- C) another awesome idea how to avoid black screen?

**Comment by roschaefer** [comment]
If you search for ["html5 smooth video transition"](https://www.google.de/search?q=html5+smooth+video+transition&oq=html5+smooth+video+transition) you will end up at the [MediaSource Api](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource). This technology looks promising for our use case but it's not the way to go. I've spend several hours and I'm getting the notion that the API is designed to implement custom buffering but cannot be abused to stitch different video files together.

**Comment by roschaefer** [comment]
Instead, css transformations seem to be a valid solution. I've found this [StackOverflow question](http://stackoverflow.com/questions/29623792/videojs-play-videos-on-a-loop-without-gaps?s=1|0.3596) mentioning a [gapless video player](https://github.com/jameshadley/LifemirrorPlayer/blob/master/LifemirrorPlayer.js) with a [live demo](http://www.lifemirror.org/films/263).

I'm going this way. We have to change [movie.js.erb](https://github.com/tino-junge/cinema-app/blob/master/app/views/movie.js.erb) quite a lot: Instead of just one ```<video>``` element, we create many of them and attach event listeners *at runtime*.
